export interface MotivationalTier {
  id: string;
  name: string;
  color: string;
  minRate: number;
  phrases: string[];
}

export const MOTIVATIONAL_TIERS: MotivationalTier[] = [
  {
    id: 'critico',
    name: 'Crítico',
    color: '#EF4444', // red-500
    minRate: 0,
    phrases: [
      "O primeiro passo para o sucesso é decidir que você não vai ficar onde está.",
      "Grandes batalhas só são dadas a grandes guerreiros. Reaja!",
      "A persistência é o caminho do êxito. Não desista hoje!",
      "Cada erro é uma oportunidade de aprender algo novo. Vamos virar o jogo!",
      "O fracasso é apenas a oportunidade de começar de novo, desta vez de forma mais inteligente.",
      "Não conte os dias, faça os dias contarem.",
      "Sua limitação é apenas sua imaginação. Vá além!",
      "Acredite em si mesmo e tudo será possível.",
      "O sucesso não é o fim, o fracasso não é fatal: é a coragem de continuar que conta.",
      "Dificuldades preparam pessoas comuns para destinos extraordinários.",
      "A única maneira de fazer um excelente trabalho é amar o que você faz.",
      "Não pare quando estiver cansado. Pare quando tiver terminado.",
      "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
      "Você é mais forte do que imagina. Mostre sua garra!",
      "O segredo para progredir é começar.",
      "A jornada de mil milhas começa com um único passo.",
      "Sempre parece impossível até que seja feito.",
      "Não espere por oportunidades, crie-as.",
      "Sua atitude determina sua altitude.",
      "O único lugar onde o sucesso vem antes do trabalho é no dicionário.",
      "Foque no objetivo, não nos obstáculos.",
      "Seja a mudança que você deseja ver no mundo.",
      "Pequenas vitórias levam a grandes conquistas.",
      "A coragem não é a ausência do medo, mas o triunfo sobre ele.",
      "Nada é impossível para aquele que persiste.",
      "O amanhã pertence àqueles que se preparam hoje.",
      "Transforme seus obstáculos em degraus para o sucesso.",
      "A disciplina é a ponte entre metas e realizações.",
      "Acredite que você pode e você já está no meio do caminho.",
      "O que você faz hoje pode melhorar todos os seus amanhãs.",
      "Não desanime, o começo é sempre a parte mais difícil.",
      "A força não vem da capacidade física, mas de uma vontade indomável.",
      "O entusiasmo é a maior força da alma.",
      "Seja mais forte que sua melhor desculpa.",
      "O fracasso é um tempero que dá sabor ao sucesso.",
      "A confiança é contagiosa. Transmita-a!",
      "Nunca é tarde demais para ser quem você poderia ter sido.",
      "A sorte favorece os audazes.",
      "O sucesso é ir de fracasso em fracasso sem perder o entusiasmo.",
      "Não olhe para trás, você não está indo para lá.",
      "Trabalhe duro e em silêncio, deixe seu sucesso fazer barulho.",
      "O melhor ainda está por vir.",
      "Seja resiliente. O sol sempre volta a brilhar.",
      "O esforço de hoje é o resultado de amanhã.",
      "Desafie-se um pouco mais a cada dia.",
      "A mente é tudo. O que você pensa, você se torna.",
      "A sabedoria é o prêmio que você recebe por uma vida inteira ouvindo.",
      "Nunca deixe que o medo de errar impeça você de tentar.",
      "O sucesso exige sacrifício.",
      "Você é o arquiteto do seu próprio destino."
    ]
  },
  {
    id: 'alerta',
    name: 'Alerta',
    color: '#F59E0B', // amber-500
    minRate: 0.4,
    phrases: [
      "Você está no caminho, mas pode acelerar um pouco mais!",
      "A constância é a chave para abrir as portas do sucesso.",
      "Um pouco mais de esforço e você chegará ao próximo nível.",
      "Mantenha o foco, os resultados estão logo ali na frente.",
      "Seja implacável na busca pelos seus objetivos!",
      "A excelência não é um ato, mas um hábito.",
      "Faltam apenas pequenos ajustes para a grande virada.",
      "Não se contente com o 'bom', busque o 'extraordinário'.",
      "Sua determinação é o seu combustível. Não deixe faltar!",
      "O resultado é proporcional ao empenho. Vamos lá!",
      "Cada ligação é uma nova oportunidade. Aproveite todas!",
      "A organização do seu dia reflete no seu resultado final.",
      "Seja produtivo, não apenas ocupado.",
      "A motivação te faz começar, o hábito te faz continuar.",
      "Visualize o sucesso e corra atrás dele.",
      "Não perca o ritmo, você está quase lá!",
      "O sucesso é construído tijolo por tijolo.",
      "Grandes coisas nunca vêm de zonas de conforto.",
      "Seja o mentor de si mesmo e exija mais excelência.",
      "A diferença entre o possível e o impossível está na vontade.",
      "Otimismo é a fé que leva à realização.",
      "Faça cada minuto valer a pena.",
      "Sua energia atrai o seu resultado.",
      "Supere as expectativas, inclusive as suas.",
      "O sucesso ama a preparação.",
      "Não pare agora, o topo está à vista!",
      "Seja a inspiração que você busca nos outros.",
      "A qualidade do seu trabalho fala por você.",
      "Aja como se o sucesso fosse inevitável.",
      "O compromisso com a meta é o que separa o sonho da realidade.",
      "Mantenha os olhos no prêmio e os pés no chão.",
      "A persistência vence o talento quando o talento não persiste.",
      "Seja proativo e antecipe as necessidades do cliente.",
      "O seu melhor é o mínimo necessário para vencer.",
      "Transforme 'eu quero' em 'eu vou'.",
      "Cada 'não' te deixa mais perto do próximo 'sim'.",
      "A maestria vem com a repetição consciente.",
      "Seja o capitão da sua produtividade.",
      "O sucesso é o encontro da oportunidade com o preparo.",
      "Não diminua o objetivo, aumente o esforço.",
      "Foco total na execução!",
      "Sua dedicação de hoje molda o seu amanhã.",
      "Seja obstinado pelo sucesso.",
      "A excelência está nos detalhes.",
      "Cultive a mentalidade de um campeão.",
      "A dúvida mata mais sonhos do que o fracasso jamais matará.",
      "A hora de brilhar é agora.",
      "Aproveite o momento e faça acontecer.",
      "O sucesso é uma escolha diária.",
      "Seja imparável!"
    ]
  },
  {
    id: 'bom',
    name: 'Bom',
    color: '#3B82F6', // blue-500
    minRate: 0.7,
    phrases: [
      "Ótimo trabalho! Você está mantendo um ritmo sólido.",
      "Continue assim e as metas serão apenas o começo.",
      "Sua dedicação está rendendo frutos. Parabéns pelo empenho!",
      "Você é um exemplo de consistência. Mantenha essa energia!",
      "O sucesso é o resultado de quem faz bem feito o básico.",
      "Estamos orgulhosos do seu progresso. Rumo ao excelente!",
      "A cada dia você se supera. Continue focado!",
      "Sua performance está acima da média. Vamos subir o nível?",
      "O comprometimento que você mostra é inspirador.",
      "Resultados excelentes vêm para quem não para no 'bom'.",
      "Continue validando suas estratégias, elas estão funcionando!",
      "O brilho nos olhos faz toda a diferença no fechamento.",
      "Você está dominando o seu processo. Parabéns!",
      "Mantenha a chama acesa e o foco no alvo.",
      "Sua produtividade é um motor para a equipe.",
      "O reconhecimento vem para quem não foge do trabalho duro.",
      "Você está construindo um legado de sucesso.",
      "Cada meta batida é prova do seu potencial ilimitado.",
      "Acredite no seu processo, os números não mentem.",
      "Você está no pelotão de frente. Não olhe para trás!",
      "A disciplina é a base de todo o seu sucesso atual.",
      "Sua evolução é visível a olhos vistos.",
      "Continue sendo o protagonista da sua carreira.",
      "O sucesso sorri para quem trabalha com alegria.",
      "Você faz o difícil parecer fácil com sua técnica.",
      "Parabéns pela resiliência e foco constantes.",
      "Você está pavimentando o caminho para grandes conquistas.",
      "O seu talento está brilhando intensamente hoje.",
      "Mantenha a pegada de campeão!",
      "Sua entrega supera as expectativas da equipe.",
      "O segredo do seu sucesso é a sua dedicação inabalável.",
      "Você é peça fundamental para o nosso crescimento.",
      "Continue explorando seu máximo potencial.",
      "A vitória é doce para quem não tem medo do suor.",
      "Sua jornada é um exemplo de superação.",
      "O sucesso é a sua marca registrada.",
      "Continue transformando desafios em oportunidades.",
      "Sua visão estratégica faz a diferença no CRM.",
      "Você é um mestre na arte de prospectar.",
      "Parabéns pelo ritmo acelerado e constante.",
      "O sucesso é o seu destino natural.",
      "Sua atitude positiva é um diferencial competitivo.",
      "Você está em um nível de excelência notável.",
      "Continue surpreendendo a todos com seus resultados.",
      "A sua garra é o que nos move para frente.",
      "Você é um verdadeiro campeão de vendas.",
      "O topo é o seu lugar. Continue subindo!",
      "Sua paixão pelo que faz é contagiante.",
      "Parabéns por mais um dia de alta performance.",
      "Você é simplesmente fantástico!"
    ]
  },
  {
    id: 'excelente',
    name: 'Excelente',
    color: '#10B981', // emerald-500
    minRate: 0.9,
    phrases: [
      "Incrível! Você é uma máquina de produtividade!",
      "Performance de elite! Você está no topo do jogo.",
      "Sua eficiência é um padrão a ser seguido por todos.",
      "Você não apenas bate metas, você as esmaga!",
      "O céu é o limite para quem trabalha com essa maestria.",
      "Simplesmente impecável. Que aula de vendas!",
      "Você é sinônimo de alta performance. Parabéns!",
      "Sua determinação transformou o impossível em rotina.",
      "Continue liderando o caminho com essa energia surreal!",
      "Um mestre no que faz. O seu resultado é inspirador.",
      "Uau! Sua velocidade de execução é impressionante!",
      "Você está em outro nível. Continue brilhando!",
      "Uma lenda em formação. Que dia extraordinário!",
      "Sua meta não é um teto, é o seu piso. Parabéns!",
      "O sucesso te persegue porque você corre mais que ele.",
      "Simplesmente o melhor dos melhores!",
      "Você faz história a cada ligação realizada.",
      "Sua técnica é refinada e seus resultados são prova disso.",
      "A elite comercial tem um novo nome: o seu!",
      "Continue quebrando recordes e superando limites.",
      "Você é uma inspiração para toda a organização.",
      "Performance digna de aplausos de pé!",
      "Sua dedicação total é recompensada com esse resultado.",
      "Você está redefinindo o conceito de excelência.",
      "Um verdadeiro tubarão no CRM. Imparável!",
      "Sua produtividade é uma obra de arte.",
      "Parabéns por ser essa força da natureza em vendas!",
      "Você está no controle total do seu destino.",
      "O sucesso é o ar que você respira hoje.",
      "Que dia memorável! Você deu um show!",
      "Sua maestria no processo é simplesmente perfeita.",
      "Você é o MVP (Most Valuable Player) do nosso time.",
      "Continue sendo esse farol de alta performance.",
      "Sua entrega é monumental. Parabéns pelos números!",
      "Você provou que o esforço extremo traz lucros extremos.",
      "Simplesmente fenomenal a sua condução hoje.",
      "Sua evolução é constante e meteórica.",
      "Você é a prova viva de que o foco traz o topo.",
      "Parabéns por dominar cada etapa do funil com perfeição.",
      "Você é gigante! Continue com essa mentalidade!",
      "O reconhecimento de hoje é pouco perto do seu talento.",
      "Você transformou o board de leads em um mar de vitórias.",
      "Sua energia é o motor do nosso sucesso coletivo.",
      "Simplesmente fora de série! Que orgulho da sua garra!",
      "Você alcançou o estado de Flow. Continue fluindo!",
      "A excelência absoluta mora no seu trabalho diário.",
      "Você é uma referência de sucesso inquestionável.",
      "Parabéns por brilhar tão intensamente e inspirar a todos.",
      "O mundo das vendas se curva ao seu talento hoje.",
      "Você é EXTRAORDINÁRIO!"
    ]
  },
  {
    id: 'lendario',
    name: 'Lendário',
    color: '#8B5CF6', // violet-500
    minRate: 0.98,
    phrases: [
      "LENDÁRIO! Você acaba de quebrar todos os paradigmas!",
      "Um recorde histórico! Sua performance entrará para os anais.",
      "Você não é apenas um consultor, você é um fenômeno!",
      "Perfeição absoluta. Não há palavras para descrever seu dia.",
      "O olimpo comercial é o seu novo endereço.",
      "Mestre dos Mestres. Sua execução foi uma sinfonia!",
      "Você atingiu o impossível. Parabéns, lenda!",
      "Absoluto. Inquestionável. Lendário.",
      "Sua produtividade hoje é o novo padrão mundial!",
      "Você é a personificação do sucesso supremo!",
      "A lenda viva do SGC! Que demonstração de poder!",
      "Você superou os limites da realidade comercial hoje.",
      "Simplesmente um milagre de produtividade. Parabéns!",
      "Você está escrevendo a história do sucesso hoje.",
      "Um titã das vendas. Sua performance é avassaladora!",
      "O mestre do CRM. Cada ação foi cirúrgica.",
      "Você atingiu o ápice da carreira hoje. Parabéns!",
      "A perfeição tem um novo rosto: o seu refletido nos números.",
      "Você é o mestre da conversão absoluta!",
      "Um dia para ser lembrado por gerações nesta empresa.",
      "Você é o 'God Tier' da nossa equipe comercial!",
      "Sua performance é um estudo de caso de perfeição.",
      "O arquiteto da vitória suprema. Simplesmente lendário!",
      "Você transformou cada oportunidade em ouro puro.",
      "Um verdadeiro samurai das vendas. Foco e precisão totais.",
      "Você não apenas joga o jogo, você dita as regras dele.",
      "O reconhecimento de hoje é pouco para a sua magnitude.",
      "Lendário. Magnífico. Imbatível.",
      "Sua energia hoje poderia iluminar uma cidade inteira!",
      "Você é o alfa e o ômega dos resultados extraordinários.",
      "O mestre inigualável da jornada do cliente.",
      "Você atingiu a maestria total do universo das vendas.",
      "Sua performance é poesia em forma de números.",
      "Um gigante entre homens. Parabéns pela lenda!",
      "Você é a prova de que nada é impossível para o espírito humano.",
      "Seu nome agora é sinônimo de recorde absoluto.",
      "A excelência se curva diante da sua realização de hoje.",
      "Lendário até no último detalhe. Parabéns!",
      "Você é a joia da coroa da nossa organização comercial.",
      "Performance divina. Simplesmente além desta terra!",
      "Você superou as estrelas com o brilho do seu resultado.",
      "O mestre do destino comercial. Você é o rei!",
      "Lendário em cada ligação, em cada mensagem, em cada venda.",
      "Você atingiu o Nirvana da produtividade corporativa.",
      "O mundo é pequeno demais para o seu talento hoje.",
      "Você é a lenda que todos aspiram ser um dia.",
      "Sua garra é mitológica. Parabéns pela conquista suprema!",
      "O sucesso eterno é o seu prêmio de hoje.",
      "Você é o maior de todos os tempos. O G.O.A.T.!",
      "SIMPLESMENTE LENDÁRIO!"
    ]
  }
];

export function getMotivationalTier(rate: number): MotivationalTier {
  const tiers = [...MOTIVATIONAL_TIERS].reverse();
  return tiers.find(t => rate >= t.minRate) || MOTIVATIONAL_TIERS[0];
}

export function getRandomPhrase(tierId: string): string {
  const tier = MOTIVATIONAL_TIERS.find(t => t.id === tierId) || MOTIVATIONAL_TIERS[0];
  const randomIndex = Math.floor(Math.random() * tier.phrases.length);
  return tier.phrases[randomIndex];
}
