export interface MotivationalTier {
  id: string;
  name: string;
  color: string;
  minRate?: number; // kept for compatibility or internal use
  phrases: string[];
}

export const MOTIVATIONAL_TIERS: MotivationalTier[] = [
  {
    id: 'critico',
    name: 'Crítico',
    color: '#EF4444', // Red 500
    phrases: [
      "Todo grande resultado começa com o primeiro passo. Vamos aquecer esses contatos?",
      "O início pode ser desafiador, mas cada tentativa conta. Que tal focar na próxima ligação?",
      "Ainda dá tempo de virar o jogo hoje! Respire fundo e vamos em frente.",
      "Todo campeão tem um começo de dia. Bora pegar esse telefone?",
      "Quebre o gelo! A próxima mensagem pode ser o início de uma grande venda.",
      "A inércia é o maior inimigo da venda. Comece agora e sinta a diferença.",
      "O 'não' você já tem, que tal buscar o 'sim' na próxima tentativa?",
      "Um motor parado não chega a lugar nenhum. Gire a chave e comece a discar.",
      "A sorte favorece quem se mantém em movimento. Vamos lá!",
      "Sua meta só depende da sua primeira ação de hoje.",
      "Não foque no volume total, foque apenas no próximo contato.",
      "Lembre-se: grandes impérios foram construídos pedra por pedra.",
      "A cada ligação, você fica mais perto da sua melhor versão.",
      "Supere o medo da rejeição. O sucesso está do outro lado da linha.",
      "Hoje é um papel em branco. Escreva uma história de superação nele.",
      "A disciplina vence o talento quando o talento não quer começar.",
      "O plantio de agora é a colheita do final do mês.",
      "Mantenha a cabeça erguida. O jogo só acaba quando termina.",
      "A prospecção é a alma do negócio. Vamos alimentar esse funil?",
      "Um minuto de coragem pode mudar todo o seu resultado diário.",
      "Não espere a motivação chegar para agir. Aja e a motivação virá.",
      "O sucesso é uma escada que começa no primeiro degrau.",
      "Você é capaz de muito mais do que imagina. Prove para si mesmo.",
      "Desafie-se a sair do zero agora mesmo!",
      "O esforço de hoje é o lucro de amanhã.",
      "Foque na solução, não no volume que ainda falta.",
      "Dê o seu melhor em cada mensagem enviada.",
      "Sua atitude hoje define sua conta bancária amanhã.",
      "A consistência é o segredo dos grandes vendedores.",
      "Transforme cada desafio em um degrau para o topo.",
      "Começar é a parte mais difícil, o resto é ritmo.",
      "Você tem o controle. Use o telefone a seu favor.",
      "O amanhã pertence a quem planta hoje.",
      "Ninguém bate metas parado. Vamos acelerar esse início?",
      "Acredite: a próxima ligação pode ser o seu maior fechamento.",
      "Seja resiliente. Cada contato te ensina algo novo.",
      "Mantenha o foco no seu propósito.",
      "O trabalho duro sempre traz recompensas.",
      "Não deixe para depois o contato que pode ser feito agora.",
      "Seja a faísca que inicia o incêndio das vendas hoje.",
      "A dedicação é o que separa os amadores dos profissionais.",
      "O tempo é o seu ativo mais valioso. Use-o com sabedoria.",
      "Vencer exige sacrifício e persistência. Vamos à luta!",
      "Nada substitui o contato direto e humano.",
      "Sua meta é o seu guia. Não a perca de vista.",
      "Todo mestre já foi um iniciante que não desistiu.",
      "O fracasso é apenas uma pausa para o próximo sucesso.",
      "Seja obstinado pelo seu progresso.",
      "O silêncio do telefone é o seu maior adversário.",
      "Vamos transformar esse 'crítico' em 'excelente' juntos?"
    ]
  },
  {
    id: 'abaixo_meta',
    name: 'Abaixo da Meta',
    color: '#F97316', // Orange 500
    phrases: [
      "Você está no caminho! Um pouco mais de ritmo e a meta estará logo ali.",
      "Bom esforço até aqui. Vamos dar aquele gás extra para alcançar o próximo nível?",
      "Quase lá! Mantenha o foco, ajuste a estratégia e os resultados virão.",
      "O aquecimento já foi feito, agora é a hora de brilhar. Vamos buscar essa meta!",
      "A engrenagem começou a girar. Não deixe o motor esfriar.",
      "Faltam poucos ajustes para você entrar no ritmo de cruzeiro.",
      "Mantenha a pressão! A constância é o que traz o resultado.",
      "Você já mostrou do que é capaz. Agora, estique só mais um pouco.",
      "O sucesso ama a velocidade. Acelere suas ações!",
      "Cada mensagem a mais agora é um passo rumo à vitória.",
      "Não pare agora, você está ganhando tração!",
      "Seja implacável na busca pelos seus números médios.",
      "A diferença entre o comum e o extraordinário é o 'extra'. Vamos dar!",
      "O ritmo atual é bom, mas o seu potencial é muito maior.",
      "Visualize a meta batida e use isso como combustível.",
      "Aperte o passo! O dia ainda tem muito a oferecer.",
      "A estratégia está certa, só falta aumentar o volume.",
      "Você está construindo uma base sólida. Continue subindo!",
      "Acredite no seu processo. A meta está ao alcance.",
      "Não se contente com o básico. Você nasceu para mais.",
      "A cada novo contato, sua confiança aumenta.",
      "Seja propositivo e direcione cada conversa para o fechamento.",
      "O progresso é viciante. Bata o próximo número!",
      "Mantenha a chama acesa. Você está quase no mediano.",
      "O reconhecimento vem para quem não desiste no meio do caminho.",
      "Aproveite o embalo e faça mais cinco contatos agora mesmo.",
      "Sua organização está melhorando. Use isso a seu favor.",
      "Foco total na execução. O resultado é consequência.",
      "Você está amadurecendo cada contato. Parabéns pelo ritmo!",
      "A persistência é o que separa os grandes dos medianos.",
      "Sinta o prazer de ver os números subindo.",
      "Sua determinação é inspiradora. Não perca o foco!",
      "A meta é um alvo que você está cada vez mais perto de atingir.",
      "Não olhe para o relógio, olhe para o telefone.",
      "Seja a energia que movimenta o time hoje.",
      "Sua melhor ligação pode ser a próxima. Vamos buscá-la!",
      "A qualidade das suas mensagens está excelente. Aumente a frequência.",
      "O sucesso é construído nos detalhes e na repetição.",
      "Você tem a técnica. Agora, use o volume.",
      "O cansaço passa, mas a satisfação da meta batida permanece.",
      "Um esforço concentrado agora fará toda a diferença no fim do dia.",
      "Seja resiliente diante das dificuldades do percurso.",
      "Seu empenho não passa despercebido. Continue focado!",
      "Transforme a ansiedade em ação produtiva.",
      "A meta é o destino, o seu trabalho é o veículo.",
      "Confie na sua capacidade de virar o jogo.",
      "Amanhã você agradecerá pelo esforço de hoje.",
      "O topo da montanha oferece a melhor vista. Continue subindo.",
      "Sua evolução é constante. Mantenha o ritmo!",
      "Vamos fechar esse gap e chegar ao topo agora?"
    ]
  },
  {
    id: 'mediano',
    name: 'Mediano',
    color: '#EAB308', // Yellow 500
    phrases: [
      "Ritmo constante e sólido! Você está entregando o esperado. Que tal irmos além?",
      "Muito bom! Seu desempenho está consistente. O próximo nível está logo ali.",
      "Você está segurando a onda muito bem hoje. Tem energia para fechar com chave de ouro?",
      "Trabalho duro reconhecido. Continue assim e o resultado será inevitável.",
      "A consistência é o segredo das vendas. Você está mandando bem!",
      "Você já garantiu o básico, agora mostre o seu diferencial.",
      "O nível médio foi atingido com sucesso. Preparado para a excelência?",
      "Sua disciplina é notável. Mantenha esse padrão e brilhe!",
      "O conforto é traiçoeiro. Vamos sair da zona mediana hoje?",
      "Parabéns pelo equilíbrio entre volume e qualidade.",
      "Você é o pilar de estabilidade que o time precisa.",
      "Continue validando suas abordagens. Elas estão funcionando.",
      "O sucesso consistente é a marca dos profissionais de elite.",
      "Sua proatividade está fazendo a diferença.",
      "Não pare no porto seguro. O oceano das grandes vendas te espera.",
      "Você domina o processo. Agora, aumente a potência!",
      "Sua performance hoje está superando a média do mercado.",
      "Mantenha a pegada. A meta está sorrindo para você.",
      "O reconhecimento de hoje é fruto da sua organização.",
      "Use esse momento para acelerar rumo ao 'bom'.",
      "Cada ligação agora é lucro puro em direção ao topo.",
      "Você está em um ritmo admirável. Continue fluindo.",
      "Sua técnica de abordagem está cada vez mais refinada.",
      "Não deixe a peteca cair. O dia está sendo produtivo!",
      "Aproveite a momentum e faça o extraordinário.",
      "Você é capaz de ditar o ritmo do seu próprio sucesso.",
      "O foco no funil está trazendo os resultados esperados.",
      "Seja o motor que impulsiona seus próprios recordes.",
      "A qualidade do seu follow-up está fazendo a diferença.",
      "Parabéns pela resiliência e foco constantes.",
      "Você está pavimentando o caminho para um mês incrível.",
      "O sucesso ama a persistência que você está mostrando.",
      "Acredite no seu potencial de quebrar a barreira do 'bom'.",
      "Sua energia atrai bons negócios. Mantenha-a alta!",
      "Visualize o topo e não pare até chegar lá.",
      "Sua dedicação é o exemplo de que o básico bem feito funciona.",
      "Aproveite a maré favorável para bater novos recordes.",
      "Você está em total controle das suas atividades hoje.",
      "O profissionalismo demonstrado é sua maior virtude.",
      "Continue sendo o protagonista da sua trajetória comercial.",
      "Sua entrega está alinhada com os objetivos da empresa.",
      "O sucesso é uma jornada e você está em ótima velocidade.",
      "Foque na conversão final. O volume já está nos trilhos.",
      "Parabéns pela maturidade comercial demonstrada hoje.",
      "Você está construindo autoridade com cada cliente.",
      "Mantenha os olhos no prêmio. Falta muito pouco!",
      "Sua disciplina hoje é a sua liberdade amanhã.",
      "Seja grato pelo progresso e ambicioso pelos próximos números.",
      "O topo está chamando. Você vai atender?",
      "Vamos transformar esse 'mediano' em 'espetacular'?"
    ]
  },
  {
    id: 'bom',
    name: 'Bom',
    color: '#84CC16', // Lime 500
    phrases: [
      "Excelente ritmo! Você está voando hoje. Quase batendo o topo da meta!",
      "Que desempenho incrível! Continue com essa energia, você está fazendo a diferença.",
      "Falta muito pouco para a excelência máxima! Seu esforço hoje está fantástico.",
      "Você é um exemplo de foco hoje. Parabéns pelos números expressivos!",
      "A meta está no bolso! Que tal esticar só mais um pouco e quebrar recordes?",
      "Você está no pelotão de elite das vendas. Mantenha a guarda alta!",
      "A velocidade com que você processa novos contatos é impressionante.",
      "Sua performance hoje é digna de um master em vendas.",
      "O reconhecimento por este volume será proporcional ao seu esforço.",
      "Não pare agora, você está em estado de flow absoluto.",
      "Você transformou o seu dia em uma máquina de fechar negócios.",
      "Sua determinação está esmagando os obstáculos.",
      "O sucesso te persegue porque você corre mais que ele.",
      "Parabéns pela capacidade de manter o foco sob pressão.",
      "Sua produtividade hoje é um benchmark para todo o time.",
      "Faltam apenas detalhes para o resultado lendário.",
      "Você é a prova de que o trabalho duro supera o talento sozinho.",
      "Continue acelerando. O topo é o seu habitat natural.",
      "Sua energia está contagiante e seus números provam isso.",
      "Você dominou o funil de prospecção hoje. Excelente!",
      "O sucesso ama quem se prepara tão bem quanto você.",
      "Mantenha a pegada de campeão até o último minuto.",
      "Você está redefinindo o que é possível em um dia de trabalho.",
      "Cada nova mensagem é uma semente de ouro que você plantou.",
      "Orgulho define o que sentimos pela sua performance de hoje.",
      "Você está em uma zona onde poucos chegam. Aproveite!",
      "Sua técnica de fechamento será testada pelos ótimos volumes de hoje.",
      "O reconhecimento da empresa será um reflexo da sua garra.",
      "Seja obstinado pela perfeição final dos números.",
      "Você é uma inspiração para os novos membros da equipe.",
      "Mantenha a humildade do aprendiz e a garra do mestre.",
      "O topo da meta é apenas o começo da sua nova jornada.",
      "Parabéns pela clareza de objetivos demonstrada hoje.",
      "Você está jogando em alto nível. Continue assim!",
      "O seu 'bom' hoje é o 'excelente' de muitos. Parabéns!",
      "Aproveite cada oportunidade gerada por esse volume incrível.",
      "Sua resiliência emocional é o segredo do seu sucesso.",
      "Você transformou prospecção em uma arte refinada.",
      "Os números não mentem: você é um top performer.",
      "Foco na qualidade final para coroar este volume fantástico.",
      "Você está pavimentando seu caminho para o bônus máximo.",
      "O sucesso te escolheu porque você nunca desistiu.",
      "Sua atitude mental positiva é o seu maior trunfo.",
      "Parabéns por superar seus próprios recordes pessoais hoje.",
      "Você está em total harmonia com o propósito comercial.",
      "A meta foi batida. Agora, vamos aniquilá-la!",
      "Sua disciplina é o motor desta alta performance.",
      "O futuro é brilhante para quem produz como você.",
      "Aproveite a glória do trabalho bem feito.",
      "Bora buscar o nível excelente agora?"
    ]
  },
  {
    id: 'excelente',
    name: 'Excelente',
    color: '#059669', // Emerald 600
    phrases: [
      "Fenomenal! Você não apenas bateu a meta, você a destruiu. Parabéns!",
      "Desempenho de elite! É esse tipo de energia que impulsiona todo o time.",
      "Simplesmente espetacular. Tire um momento para celebrar seu trabalho duro hoje!",
      "Você atingiu o topo! Um verdadeiro show de produtividade e foco.",
      "Fora da curva! O seu esforço de hoje é a definição de alta performance.",
      "Você é uma lenda viva do SGC. Resultados extraordinários!",
      "Mestre das vendas. Sua performance foi uma sinfonia de acertos.",
      "O céu não é o limite para quem produz com essa maestria.",
      "Parabéns por redefinir o conceito de excelência comercial.",
      "Sua dedicação total foi recompensada com este resultado épico.",
      "Você é o MVP indiscutível do dia de hoje.",
      "Simplesmente imparável. Que demonstração de força mental!",
      "A perfeição tem um novo nome: o seu nos relatórios.",
      "Obrigado por elevar o sarrafo de toda a organização.",
      "Seu volume de hoje é um exemplo de foco absoluto.",
      "Você atingiu o estado de mestre na arte da prospecção.",
      "Nada é impossível para quem tem a sua garra e técnica.",
      "Celebre! Você conquistou o que poucos ousam tentar.",
      "Você é o motor que move esta empresa para frente.",
      "Sua produtividade hoje é o novo padrão de ouro.",
      "Simplesmente magnífico. Cada ação foi cirúrgica.",
      "Você provou que os limites só existem na nossa mente.",
      "O sucesso absoluto é o seu prêmio por não ter parado.",
      "Sua energia de hoje é o combustível dos nossos sonhos.",
      "Você é o capitão do seu sucesso. Continue no comando!",
      "Performance divina. Além das expectativas mais otimistas.",
      "Parabéns por ser um gigante entre os profissionais.",
      "Sua jornada de hoje é um estudo de caso de sucesso.",
      "Você transformou o CRM em um mar de oportunidades.",
      "O reconhecimento de hoje é apenas o começo da sua glória.",
      "Você é o arquiteto da vitória suprema de hoje.",
      "Sua maestria no processo comercial é inquestionável.",
      "Parabéns por brilhar tão intensamente e guiar o time.",
      "Você alcançou o patamar mais alto da performance humana.",
      "Sua disciplina transformou desejos em fatos concretos.",
      "O mundo das vendas se curva ao seu talento hoje.",
      "Você é um verdadeiro samurai das metas. Precisão total.",
      "A satisfação do dever cumprido é o seu melhor bônus.",
      "Parabéns por esmagar cada desafio com um sorriso no rosto.",
      "Você é simplesmente épico! Continue sendo extraordinário.",
      "Sua resiliência moldou este resultado inalcançável.",
      "O sucesso ama quem trabalha tão duro quanto você.",
      "Você é a joia da coroa da nossa estratégia comercial.",
      "Mantenha essa mentalidade de vencedor para sempre.",
      "Você superou as estrelas com o brilho deste resultado.",
      "O mestre do destino comercial. Você é o rei do dia!",
      "Lendário em cada ação. Parabéns pela excelência!",
      "Você atingiu a perfeição na execução diária.",
      "O topo é pouco para o seu talento. Continue voando!",
      "SIMPLESMENTE O MELHOR DOS MELHORES!"
    ]
  }
];

export function getMotivationalTier(volume: number): MotivationalTier {
  if (volume <= 30) return MOTIVATIONAL_TIERS[0]; // critico
  if (volume <= 50) return MOTIVATIONAL_TIERS[1]; // abaixo_meta
  if (volume <= 80) return MOTIVATIONAL_TIERS[2]; // mediano
  if (volume <= 100) return MOTIVATIONAL_TIERS[3]; // bom
  return MOTIVATIONAL_TIERS[4]; // excelente
}

export function getRandomPhrase(tierId: string): string {
  const tier = MOTIVATIONAL_TIERS.find(t => t.id === tierId) || MOTIVATIONAL_TIERS[0];
  const randomIndex = Math.floor(Math.random() * tier.phrases.length);
  return tier.phrases[randomIndex];
}

export function getMotivationalPhrase(volume: number): string {
  const tier = getMotivationalTier(volume);
  return getRandomPhrase(tier.id);
}
